export default  {
  GET_COURSES: 'GET_COURSES',
  GET_PRICES: 'GET_PRICES',
  WRITE_TOKEN: 'WRITE_TOKEN',
  GET_TOKEN: 'GET_TOKEN',
  GET_SINGLE_COURSE: 'GET_SINGLE_COURSE',
  GET_SINGLE_PRICE: 'GET_SINGLE_PRICE',
  
  FULFILLED: '_FULFILLED',
  REJECTED: '_REJECTED',
  PENDING: '_PENDING',
};